name: GitHub Actions without Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
          POSTGRES_USER: ${{env.PSQL_USER}}
          POSTGRES_PASSWORD: ${{ env.PSQL_PASS}}
          POSTGRES_DB: ${{ env.PSQL_DB}}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: make migrations
        run: |
          python install pytest
          python manage.py makemigratios
      - name: Migrate
        run: |
          python manage.py migrate
      - name: Test
        run: |
          pytest
      - name: Run server    
        run: 
          python manage.py runserver